## Import relevant libraries

In [2]:
import numpy as np

## Dot Product

In [5]:
x = np.array([2, 8, -4])
y = np.array([1, -7, 3])

In [6]:
np.dot(x, y)

-66

In [8]:
u = np.array([0, 2, 5, 8])
v = np.array([20, 3, 4, -1])

In [9]:
np.dot(u, v)

18

## Scalar * Scalar

In [10]:
np.dot(5, 6)

30

In [11]:
np.dot(10, -2)

-20

## Scalar * Vector

In [12]:
x

array([ 2,  8, -4])

In [13]:
np.dot(5, x)

array([ 10,  40, -20])

In [17]:
c = np.array([[-12, 5 ,-5, 1, 6], [6, -2, 0, 0, -3], [10, 2, 0, 8, 0], [9, -4, 8, 3, -6]])
c

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [18]:
d = np.array([[6, -1], [8, -4], [2, -2], [7, 4], [-6, -9]])
d

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [19]:
np.dot(c, d)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 95,  57]])