In [1]:
import numpy as np

## np.empty(), np.zeros(), np.ones(), np.full()

In [2]:
array_empty = np.empty(shape = (2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
array_0 = np.zeros(shape = (2,3))
array_0

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
array_one = np.ones(shape = (2,3))
array_one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
array_full = np.full(shape = (2,3), fill_value = 'AaA')
array_full

array([['AaA', 'AaA', 'AaA'],
       ['AaA', 'AaA', 'AaA']], dtype='<U3')

## "_like' functions

In [6]:
matrix_a = np.array([[1,0,9,2,2], [2,23,4,5,1], [0,2,3,4,1]])
matrix_a

array([[ 1,  0,  9,  2,  2],
       [ 2, 23,  4,  5,  1],
       [ 0,  2,  3,  4,  1]])

In [7]:
array_empty_like = np.empty_like(matrix_a)
array_empty_like

array([[                  0,                   0, 4607182418800017408,
        4589168020290535424, 4598175219545276416],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4617385886705778688],
       [4612248968380809216, 4607182418800017408, 4625196817309499392,
        4616189618054758400, 4607182418800017408]])

In [8]:
array_0s_like = np.zeros_like(matrix_a)
array_0s_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

## np.arange()

In [9]:
list(range(30))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [10]:
array_rng = np.arange(30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [11]:
array_rng = np.arange(stop = 30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
array_rng = np.arange(start = 0, stop = 30)
array_rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
array_rng = np.arange(start = 0, stop = 30, step = 2.5)
array_rng

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5])

In [15]:
array_rng = np.arange(start = 0, stop = 30, step = 2.5, dtype = np.int32) # 30 / 2.5 = 12 elements
array_rng

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22], dtype=int32)

## Random Generators

### Defining Random Generators

In [16]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [17]:
array_RG = gen(pcg())
array_RG.normal(size = (5,5))

array([[-0.13641002, -1.20997107,  0.26877041, -2.05038297, -0.13447488],
       [ 0.84827602, -0.57275103,  1.21293826,  0.60481981,  1.81478933],
       [ 0.4972552 , -0.26762812, -0.60619137,  1.76913872, -1.29938849],
       [-1.56323377, -0.19434227,  0.31993053, -0.31272624, -0.71362558],
       [-1.62352341,  0.19446557, -0.11090016,  1.36048527, -0.57674223]])

In [18]:
array_RG = gen(pcg(seed = 365))
array_RG.normal(size = (5,5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

In [19]:
# A seed only lastss for one execution of a method or function before it is reset
array_RG.normal(size = (5,5))

array([[-0.76065577,  1.48158358,  0.01200258, -0.06846959,  0.25301664],
       [-0.52640788,  0.79613109,  0.28203421,  1.80238008,  0.93932117],
       [-0.53693283, -0.26317689, -1.77723035,  1.14900013, -2.20733915],
       [ 1.54116775, -0.5124932 , -2.14564563,  1.98878673,  0.32208907],
       [-1.2651495 ,  3.2714633 ,  1.78650493, -0.20233675,  0.20427467]])

### Generating Integers, Probabilities and Random Choices

In [20]:
array_RG = gen(pcg(seed = 365))
array_RG.integers(low = 10, high = 100, size = (5,5))

array([[18, 78, 64, 78, 84],
       [66, 67, 28, 10, 69],
       [45, 15, 37, 74, 96],
       [19, 21, 89, 73, 54],
       [53, 84, 66, 51, 92]])

In [21]:
# continuos uniform distribution
array_RG = gen(pcg(seed = 365))
array_RG.random(size = (5,5)) # random numbers between 0 and 1

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [22]:
# The method defaults to using discrete uniform distribution
# Choices and their probabilities to occur
array_RG = gen(pcg(seed = 365))
array_RG.choice([1,2,3,4,5], p = [0.1, 0.1, 0.1, 0.1, 0.6] ,size = (5,5))

array([[5, 5, 5, 3, 5],
       [1, 5, 2, 5, 5],
       [5, 5, 1, 5, 4],
       [3, 5, 5, 5, 5],
       [5, 1, 5, 5, 2]])

### Generating Arrays From Known Distributions

In [25]:
# Over a fixed interval of time distance, or space we expect an event to occur exactly once
array_RG = gen(pcg(seed = 365))
array_RG.poisson(lam = 2, size = (5,5))

array([[3, 1, 1, 4, 2],
       [3, 1, 2, 2, 2],
       [2, 2, 2, 2, 3],
       [2, 2, 4, 1, 1],
       [1, 3, 3, 1, 2]])

In [26]:
'''
Measures how many times a certain outcome can appear over a series of trials,
where there are only 2 possible outcome
n= number of trials, p = probability of getting our desired outcome
'''

array_RG = gen(pcg(seed = 365))
array_RG.binomial(n = 100, p = 0.4, size = (5,5))

array([[42, 44, 30, 36, 45],
       [36, 41, 38, 42, 41],
       [35, 31, 35, 46, 29],
       [41, 41, 46, 34, 48],
       [45, 45, 45, 40, 43]])

In [27]:
# Each element is a possible outcome of a logistic distribution with loc = 9 and scale = 1.2
array_RG = gen(pcg(seed = 365))
array_RG.logistic(loc = 9, scale = 1.2, size = (5,5))

array([[10.37767822, 10.42451863,  9.63404367,  7.36153427,  9.82286787],
       [ 5.81223125, 10.09354231,  6.46790532, 11.38740256,  8.97147918],
       [10.85844698,  8.79081317,  5.962079  ,  9.99560681,  8.34539118],
       [ 7.97105522,  8.9981544 ,  8.93530194,  9.6253307 ,  9.23850869],
       [ 9.73729284,  5.3090678 , 10.13723528, 11.04372782,  7.11078651]])

https://numpy.org/doc/stable/reference/random/generator

### Applications of Random Generators

In [29]:
array_RG = gen(pcg(seed = 365))

array_column_1 = array_RG.normal(loc = 2, scale = 3, size = (1000))
array_column_2 = array_RG.normal(loc = 7, scale = 2, size = (1000))
array_column_3 = array_RG.logistic(loc = 11, scale = 3, size = (1000))
array_column_4 = array_RG.exponential(scale = 4, size = (1000))
array_column_5 = array_RG.geometric(p = 0.7, size = (1000))

In [31]:
random_test_data = np.array([array_column_1, array_column_2, array_column_3, array_column_4, array_column_5]).transpose()
random_test_data

array([[ 1.59077303,  6.42174295, 10.14698427,  6.91500737,  1.        ],
       [ 2.28243293,  8.57902322, 15.93309953,  6.243605  ,  1.        ],
       [ 1.81098674,  5.17270135, -0.46878789,  2.44997251,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  2.66485989,  0.80935387,  1.        ],
       [-2.21015722,  8.2176402 , 12.69328115,  0.50644607,  2.        ],
       [ 2.91161235,  7.90337695, 11.79840961,  4.86816939,  1.        ]])

In [32]:
random_test_data.shape

(1000, 5)

In [33]:
np.savetxt("Random-Test-from-NumPy.csv", random_test_data, fmt = "%s", delimiter = ",")

In [35]:
np.genfromtxt("Random-Test-from-NumPy.csv", delimiter = ",")

array([[ 1.59077303,  6.42174295, 10.14698427,  6.91500737,  1.        ],
       [ 2.28243293,  8.57902322, 15.93309953,  6.243605  ,  1.        ],
       [ 1.81098674,  5.17270135, -0.46878789,  2.44997251,  1.        ],
       ...,
       [ 0.1973629 ,  4.3465854 ,  2.66485989,  0.80935387,  1.        ],
       [-2.21015722,  8.2176402 , 12.69328115,  0.50644607,  2.        ],
       [ 2.91161235,  7.90337695, 11.79840961,  4.86816939,  1.        ]])