# Generating Data with Numpy

### 1. Run these next few cells:

In [1]:
import numpy as np

In [19]:
array_1D = np.array([10,11,12,13, 14])
array_1D

array([10, 11, 12, 13, 14])

In [20]:
array_2D = np.array([[20,30,40,50,60], [43,54,65,76,87], [11,22,33,44,55]])
array_2D

array([[20, 30, 40, 50, 60],
       [43, 54, 65, 76, 87],
       [11, 22, 33, 44, 55]])

In [21]:
array_3D = np.array([[[1,2,3,4,5], [11,21,31,41,51]], [[11,12,13,14,15], [51,52,53,54,5]]])
array_3D

array([[[ 1,  2,  3,  4,  5],
        [11, 21, 31, 41, 51]],

       [[11, 12, 13, 14, 15],
        [51, 52, 53, 54,  5]]])

### 2. Generate 4 arrays of size 10:
    A) The first one should be "empty"
    B) The second one should be full of 0s
    C) The third one should be full of 1s
    D) The last one should be full of 2s
   (<b>Hint</b>: Try to use 4 different functions here.)

In [8]:
array_empty = np.empty(shape = 10)
array_empty

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
array_zeros = np.zeros(shape = 10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
array_ones = np.ones(shape = 10)
array_ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
array_full = np.full(shape = 10, fill_value = 2)
array_full

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### 3. Generate 4 more arrays. This time, they should be 2 by 4 arrays. 

In [15]:
array_empty = np.empty(shape = (2,4))
array_empty

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
array_zeros = np.zeros(shape = (2,4))
array_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
array_ones = np.ones(shape = (2,4))
array_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
array_full = np.full(shape = (2,4), fill_value = 2)
array_full

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

### 4. Use the <i> _like </i> functions to generate 4 more arrays:
    A) An empty array with the same shape as array_1D. 
    B) An 2-D array of 0s with the same shape as array_2D.
    C) A 3-D array of 1s with the same shappe as array_3D.
    D) A 3-D array of 2s with the same shape as array_3D. 

In [26]:
array_empty_like = np.empty_like(array_1D)
array_empty_like

array([0, 0, 0, 0, 0])

In [29]:
array_empty_zeros = np.zeros_like(array_2D)
array_empty_zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [31]:
array_empty_ones = np.ones_like(array_3D)
array_empty_ones

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [33]:
array_empty_full = np.full_like(array_3D, fill_value = 2)
array_empty_full

array([[[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])

### 5. With the help of the np.arange() function, generate several sequences of numbers:
    A) The integers from 0 to 50, excluding 50. 
    B) The integers from 1 to 50, including 50. 
    C) The integers from 25 to 50, including 50. 
    D) Every 5-th integers from 25 to 50, including 50. 
    E) Every 5-th integers from 25 to 50, including 50, represented as decimals of up to 32 bits. 

In [34]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [35]:
np.arange(1,51)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [36]:
np.arange(25, 51)

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50])

In [37]:
np.arange(25,51,5)

array([25, 30, 35, 40, 45, 50])

In [38]:
np.arange(25,51,5, np.float32)

array([25., 30., 35., 40., 45., 50.], dtype=float32)

### 6. Import the following functions from the numpy.random module:
    A) Generator as "gen".
    B) PCG64 as "pcg"

In [40]:
from numpy.random import Generator as gen

In [41]:
from numpy.random import PCG64 as pcg

### 7. Create a random generator object.

In [42]:
array_RG = gen(pcg())

### 8. Using the .random() method, generate the following pseudo-random values:
    A) A single probability of an event occuring.
    B) An array of size 10 with the probabilities of 10 events. 
    C) A 5 by 10 2-D array with the probabilities of 50 events.  

In [44]:
array_RG.normal()

1.6401438462703861

In [46]:
array_RG.normal(size = 10)

array([ 1.9114947 ,  0.27627915,  1.27437423, -0.3099697 , -0.79533154,
        0.82022817, -0.44378275,  0.6292194 ,  0.77011848,  0.58120864])

In [47]:
array_RG.normal(size = (5,10))

array([[-0.4710503 ,  0.78471875, -1.34216919,  0.24448552, -2.0530318 ,
        -1.46323667, -0.66972288,  0.12426841,  0.67768854, -0.31102777],
       [ 1.30802135, -2.13805053, -0.18034242, -0.34167615,  0.72929513,
        -0.79179404,  0.78923599,  1.14872372, -0.68909503,  0.61790003],
       [-0.17186737,  1.3564089 ,  0.70264399, -1.70301739,  1.12697282,
         0.62370913,  2.59974143,  1.04055197,  1.71608484, -0.2187836 ],
       [ 0.44902281, -1.07138623, -0.95775617, -0.40085316,  0.29384767,
         0.72453205,  0.18213198, -1.04829255, -0.45940207,  0.50806934],
       [ 0.9909411 , -0.60305778, -0.20718651,  0.0668644 , -0.55053906,
        -0.68671212,  0.92243822,  1.24966936, -0.74322042,  0.83284572]])

### 9. Set the seed for the random generator to 123, and generate the same 3 sets of values:
    A) A single probability of an event occuring.
    B) An array of size 10 with the probabilities of 10 events. 
    C) A 5 by 10 2-D array with the probabilities of 50 events.  
   <b> Note: </b> The seed only lasts for a single method before it gets reset. Hence, make sure you define the seed before calling the method every time. 

In [49]:
array_RG = gen(pcg(seed = 123))
array_RG.random()

0.6823518632481435

In [50]:
array_RG = gen(pcg(seed = 123))
array_RG.random(10)

array([0.68235186, 0.05382102, 0.22035987, 0.18437181, 0.1759059 ,
       0.81209451, 0.923345  , 0.2765744 , 0.81975456, 0.88989269])

In [52]:
array_RG = gen(pcg(seed = 123))
array_RG.random(size = (5,10))

array([[0.68235186, 0.05382102, 0.22035987, 0.18437181, 0.1759059 ,
        0.81209451, 0.923345  , 0.2765744 , 0.81975456, 0.88989269],
       [0.51297046, 0.2449646 , 0.8242416 , 0.21376296, 0.74146705,
        0.6299402 , 0.92740726, 0.23190819, 0.79912513, 0.51816504],
       [0.23155562, 0.16590399, 0.49778897, 0.58272464, 0.18433799,
        0.01489492, 0.47113323, 0.72824333, 0.91860049, 0.62553401],
       [0.91712257, 0.86469025, 0.21814287, 0.86612743, 0.73075194,
        0.27786529, 0.79704355, 0.86522171, 0.2994379 , 0.52704208],
       [0.07148681, 0.58323841, 0.2379064 , 0.76496365, 0.17363164,
        0.31274226, 0.01447448, 0.03255192, 0.49670184, 0.46831253]])

### 10. Set the seed for the random generator to 123, and generate the following arrays of integers:
    A) A single integer between 0 and 10.
    B) A 1-D array of 10 integers between 0 and 100.
    C) A 5 by 10 array of two-digit integers.

In [53]:
array_RG = gen(pcg(seed = 123))
array_RG.integers(10)

0

In [54]:
array_RG = gen(pcg(seed = 123))
array_RG.integers(10, size = 10)

array([0, 6, 5, 0, 9, 2, 2, 1, 3, 1])

In [56]:
array_RG = gen(pcg(seed = 123))
array_RG.integers(10, size = (5,10))

array([[0, 6, 5, 0, 9, 2, 2, 1, 3, 1],
       [3, 8, 4, 9, 4, 2, 7, 8, 8, 8],
       [0, 5, 2, 2, 2, 8, 7, 2, 4, 7],
       [1, 6, 4, 9, 7, 2, 8, 7, 2, 5],
       [7, 2, 2, 1, 0, 4, 0, 5, 4, 1]])

### 11. For this next bit, check the NumPy documentation and select 3 different probability distributions (e.g. normal, poisson, binomial, logistic) and generate the following:
    A) One "default" value from one distribution (without specifying any non-mandatory arguments).
    B) An array of 10 values from the second distribution. 
    C) A 5 by 10 2-D array with values from the third distribution.

In [57]:
array_RG = gen(pcg(seed = 123))
array_RG.normal()

-0.9891213503478509

In [58]:
array_RG = gen(pcg(seed = 123)) 
array_RG.poisson(size = 10, lam = 15)

array([17, 11, 11, 22, 15, 19, 18, 22, 19, 12])

In [59]:
array_RG = gen(pcg(seed = 123)) 
array_RG.binomial(n = 100, p = 0.7, size = (5,10))

array([[67, 67, 72, 59, 77, 72, 81, 79, 67, 67],
       [62, 63, 72, 65, 77, 68, 73, 71, 69, 70],
       [72, 69, 72, 78, 70, 75, 61, 75, 72, 74],
       [75, 72, 70, 60, 77, 67, 70, 73, 67, 68],
       [59, 66, 65, 67, 76, 65, 68, 73, 66, 67]])