In [34]:
import numpy as np

In [35]:
lending_company_data_numeric_1 = np.loadtxt("Lending-Company-Numeric-Data.csv", delimiter = ',')
lending_company_data_numeric_1


array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [36]:
lending_company_data_numeric_2 = np.genfromtxt("Lending-Company-Numeric-Data.csv", delimiter = ',')
lending_company_data_numeric_2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [37]:
np.array_equal(lending_company_data_numeric1, lending_company_data_numeric_2)

True

In [38]:
# They are saved as a plain text rather than number

# All the values now have sinlge quotes around them

# We can use this way of importing dataset only if we want to observe the data values that have been stored in it,
# and we DON'T need to execute any mathematical operations 
lending_company_data_numeric_NAN = np.loadtxt("Lending-Company-Numeric-Data-NAN.csv",
                                             delimiter = ';',
                                             dtype = str)
lending_company_data_numeric_NAN

array([['2000', '40', '365', '3121', '4241', '13621'],
       ['2000', '40', '365', '3061', '4171', '15041'],
       ['1000', '40', '365', '2160', '3280', '15340'],
       ...,
       ['', '40', '365', '4201', '5001', '16600'],
       ['1000', '40', '365', '2080', '3320', '15600'],
       ['2000', '40', '365', '4601', '4601', '16600']], dtype='<U5')

In [39]:
lending_company_data_numeric_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter = ';')
lending_company_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

## Partial Cleaning While Importing

In [40]:
lending_company_data_numeric_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv", delimiter = ';')
lending_company_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [41]:
lending_company_data_numeric_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",
                                                 delimiter = ';', 
                                                 skip_header = 2)
lending_company_data_numeric_NAN

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [42]:
lending_company_data_numeric_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",
                                                 delimiter = ';', 
                                                 skip_footer = 2)
lending_company_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]])

In [43]:
lending_company_data_numeric_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",
                                                 delimiter = ";", 
                                                 usecols = (0,1,5))
lending_company_data_numeric_NAN

array([[ 2000.,    40., 13621.],
       [ 2000.,    40., 15041.],
       [ 1000.,    40., 15340.],
       ...,
       [   nan,    40., 16600.],
       [ 1000.,    40., 15600.],
       [ 2000.,    40., 16600.]])

In [44]:
lending_company_data_numeric_NAN = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",
                                                 delimiter = ';', 
                                                 skip_header = 2,
                                                 skip_footer = 2,
                                                 usecols = (0,1,5))
lending_company_data_numeric_NAN

array([[ 1000.,    40., 15340.],
       [ 2000.,    40., 15321.],
       [ 2000.,    50., 13720.],
       ...,
       [ 2000.,    40., 16600.],
       [ 2000.,    40., 16600.],
       [   nan,    40., 16600.]])

In [45]:
# Splitting ( unpacking ) the output one for each variable
lending_co_data_5, lending_co_data_0, lending_co_data_1 = np.genfromtxt("Lending-Company-Numeric-Data-NAN.csv",
                                                                        delimiter = ';', 
                                                                        skip_header = 2,
                                                                        skip_footer = 2,
                                                                        usecols = (5,0,1),
                                                                        unpack = True)
lending_company_data_numeric_NAN

array([[ 1000.,    40., 15340.],
       [ 2000.,    40., 15321.],
       [ 2000.,    50., 13720.],
       ...,
       [ 2000.,    40., 16600.],
       [ 2000.,    40., 16600.],
       [   nan,    40., 16600.]])