# Introduction to NumPy

## Exercises:

### 1. Update/Upgrade the NumPy package to the latest version

In [2]:
# Parts 1 and 2 can be executed in Jupyter or the Anacodna Prompt
!pip install -U numpy

### 2. Install/Upgrade another package (e.g. Pandas) 

In [3]:
!pip install -U Pandas

  Obtaining dependency information for Pandas from https://files.pythonhosted.org/packages/f8/c7/cfef920b7b457dff6928e824896cb82367650ea127d048ee0b820026db4f/pandas-2.0.3-cp39-cp39-macosx_10_9_x86_64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 341.8/341.8 kB 1.6 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 10.7 MB/s eta 0:00:0000:0100:01
  Attempting uninstall: Pandas
    Found existing installation: pandas 1.3.5
    Uninstalling pandas-1.3.5:
      Successfully uninstalled pandas-1.3.5


### 3. Import NumPy as <i> np </i>

In [5]:
import numpy as np

### 4. Use the<i> np.array() </i>function to create an array variable - <i>array_hw_1</i> with the numbers 4,5,7 and 10 in it

In [7]:
array_hw_1 = np.array([4, 5, 7, 10])

### 5. Display the new array on screen

In [8]:
array_hw_1

array([ 4,  5,  7, 10])

### 6. Create a 2x2 array with the same values as <i> array_hw_1 </i> and display it on the screen

In [13]:
array_hw_2 = np.array([[4,5], [7, 10]])

In [14]:
array_hw_2

array([[ 4,  5],
       [ 7, 10]])

### 7. Call the <i> np.mean() </i> function on each array

In [19]:
np.mean(array_hw_1)

6.5

In [25]:
np.mean(array_hw_2)

6.5

### 8. Use the <i> axis </i> argument to find the mean for all the rows of <i> array_hw_2</i>

In [27]:
np.mean(array_hw_2, axis = 1)

array([4.5, 8.5])

### 9. Use the <i>axis</i> argument to find the mean for all the columns of <i>array_hw_2</i>

In [28]:
np.mean(array_hw_2, axis = 0)

array([5.5, 7.5])

### 10. Use the <i> Shift + Tab </i> shorcut on <i> np.mean() </i> to check what possible arguments we can specify. 

### 11. Set the <i> dtype </i> argument equal to <i> np.int </i> and compare the results 

In [36]:
np.mean(array_hw_2, axis = 0, dtype = np.int32)

array([5, 7], dtype=int32)