## Packages

In [1]:
import numpy as np

In [2]:
# Stop NumPy from using scientific notation to express the numbers.
# Extend the numbers of characters we fit i a sinle line output to 100.
# Only display 2 digits after decimal point.
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

## Importing the Data

In [3]:
raw_data = np.genfromtxt("loan-data.csv", 
                         delimiter = ';', 
                         skip_header = 1, 
                         autostrip = True)
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

## Checking for Incomplete Data

In [4]:
np.isnan(raw_data).sum()

88005

In [5]:
# There must exist entire columns full of only NaNs or strings
temporary_fill = np.nanmax(raw_data) + 1
temporary_mean = np.nanmean(raw_data, axis = 0)

/var/folders/q7/w_hh_4ds07n_pl9zc0p1wxbc0000gn/T/ipykernel_4491/105770568.py:3: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data, axis = 0)


In [6]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [7]:
temporary_stat = np.array([np.nanmin(raw_data, axis = 0), 
                           temporary_mean, 
                           np.nanmax(raw_data, axis = 0)])

/var/folders/q7/w_hh_4ds07n_pl9zc0p1wxbc0000gn/T/ipykernel_4491/3892447211.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stat = np.array([np.nanmin(raw_data, axis = 0),
/var/folders/q7/w_hh_4ds07n_pl9zc0p1wxbc0000gn/T/ipykernel_4491/3892447211.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data, axis = 0)])


In [8]:
# 2D array that holds 3 one-dimensional arrays
temporary_stat

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset

### Splitting the Columns

In [9]:
'''
1- np.isnan returns true for NaNs
2- np.argwhere checks (value != 0) and returns the index
'''
column_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [10]:
column_numeric = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
column_numeric

array([ 0,  2,  4,  6,  7, 13])

### Re-imporrting the Dataset

In [11]:
loan_string_data = np.genfromtxt("loan-data.csv", 
                         delimiter = ';', 
                         skip_header = 1, 
                         autostrip = True, 
                         usecols = column_strings, 
                         dtype = str)
loan_string_data

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [12]:
# handled missing values among strings and numbers differently
loan_numeric_data = np.genfromtxt("loan-data.csv", 
                                  delimiter = ";", 
                                  skip_header = 1, 
                                  autostrip = True, 
                                  usecols = column_numeric, 
                                  filling_values = temporary_fill)
loan_numeric_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

## Naming columns

In [13]:
header_full = np.genfromtxt("loan-data.csv", 
                            delimiter = ";", 
                            autostrip = True, 
                            skip_footer = raw_data.shape[0], 
                            dtype = str)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [14]:
header_string, header_numeric = header_full[column_strings], header_full[column_numeric]

In [15]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [16]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Creating Checkpoints

In [17]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [18]:
checkpoint_test = checkpoint("checkpoint-test", header_string, loan_string_data)

In [19]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [20]:
np.array_equal(checkpoint_test['data'], loan_string_data)

True

## Manipulating String Columns

In [21]:
header_string

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [22]:
header_string[0] = "issue_date"

In [23]:
loan_string_data

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

### Issue Date

In [24]:
np.unique(loan_string_data[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [25]:
np.chararray.strip([loan_string_data[:,0]], "-15")

chararray([['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec']], dtype='<U69')

In [26]:
loan_string_data[:,0] = np.chararray.strip([loan_string_data[:,0]], "-15")

In [27]:
np.unique(loan_string_data[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [28]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [29]:
for i in range(13):
    loan_string_data[:,0] = np.where(loan_string_data[:,0] == months[i], 
                                     i, 
                                     loan_string_data[:,0])

In [30]:
np.unique(loan_string_data[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [31]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [32]:
'''
Seperating status to good or bad
1-> good, 0-> bad
'''
np.unique(loan_string_data[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [33]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [34]:
loan_string_data[:,1] = np.where(np.isin(loan_string_data[:,1], status_bad),0,1)

In [35]:
np.unique(loan_string_data[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [36]:
header_string

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [37]:
np.unique(loan_string_data[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [38]:
loan_string_data[:,2] = np.chararray.strip(loan_string_data[:,2], " months")
loan_string_data[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [39]:
header_string[2] = 'term_months'

In [40]:
loan_string_data[:,2] = np.where(loan_string_data[:,2] == '', 
                                 '60', 
                                 loan_string_data[:,2])
loan_string_data[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [41]:
# could just use 1 and 0 instead but do not know the context
np.unique(loan_string_data[:,2])

array(['36', '60'], dtype='<U69')

### Grade and Subgrade

In [42]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [43]:
np.unique(loan_string_data[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [44]:
np.unique(loan_string_data[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

#### Filling Sub Grade 

In [45]:
for i in np.unique(loan_string_data[:,3])[1:]:
    loan_string_data[:,4] = np.where((loan_string_data[:,4] == '') & (loan_string_data[:,3] == i), 
                                     i + '5', 
                                     loan_string_data[:,4])

In [46]:
np.unique(loan_string_data[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [47]:
loan_string_data[:,4] = np.where(loan_string_data[:,4] == '', 
                                 'H1', 
                                 loan_string_data[:,4])

In [48]:
np.unique(loan_string_data[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

#### Removing Grade

In [49]:
# dataset, index, row-col
loan_string_data = np.delete(loan_string_data, 3, axis = 1)

In [50]:
loan_string_data[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [51]:
header_string = np.delete(header_string, 3)

In [52]:
# column matches with its content
header_string[3]

'sub_grade'

#### Converting Sub Grade

In [53]:
np.unique(loan_string_data[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [54]:
loan_string_data[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [55]:
keys = list(np.unique(loan_string_data[:,3]))
values = list(range(1, np.unique(loan_string_data[:,3]).shape[0] + 1))
dict_sub_grade = dict(zip(keys, values))

In [56]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [57]:
for i in np.unique(loan_string_data[:,3]):
    loan_string_data[:,3] = np.where(loan_string_data[:,3] == i, 
                                    dict_sub_grade[i], 
                                    loan_string_data[:,3])

In [58]:
np.unique(loan_string_data[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

## Verification Status

In [59]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [60]:
np.unique(loan_string_data[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [61]:
loan_string_data[:,4] = np.where((loan_string_data[:,4] == '') | (loan_string_data[:,4] == 'Not Verified'), 0, 1)

In [62]:
np.unique(loan_string_data[:,4])

array(['0', '1'], dtype='<U69')

## URL

In [63]:
loan_string_data[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [64]:
np.chararray.strip(loan_string_data[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [65]:
loan_string_data[:,5] = np.chararray.strip(loan_string_data[:,5], 
                                           "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [66]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [67]:
loan_numeric_data[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [68]:
loan_string_data[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [69]:
'''
The URL column does not hold any additional information we can't already extract from the id column
So getting rid of the URLs seems like a good decision
'''
np.array_equal(loan_numeric_data[:,0].astype(dtype = np.int32), loan_string_data[:,5].astype(dtype = np.int32))

True

In [70]:
loan_string_data = np.delete(loan_string_data, 5, axis = 1)
header_string = np.delete(header_string, 5)

In [71]:
loan_string_data[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [72]:
header_string[5]

'addr_state'

In [73]:
loan_numeric_data[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [74]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## State Address

In [75]:
header_string

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [76]:
header_string[5] = "state_address"

In [77]:
'''
Iowa (IA) was purposefully left as a baseline benchmark

When doing analysis on a variable with many categories, it is normal to pick one as a benchmark and include 
dummy variables for the rest.
'''
np.unique(loan_string_data[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [78]:
'''
There are more applications with missing or unreported addresses than there are for 45 of the other states

We have very little data for many states to examine each one individually, if we assign a unique value to each state,
this will allow outliers to have a big influence on the coefficients.

The more categories a variable has, the fewer data will be available for each one
'''

#                            states_names                   , states_count
states_names, states_count = np.unique(loan_string_data[:,5], return_counts = True)
states_count_sorted = np.argsort(-states_count) # descending order
states_names[states_count_sorted], states_count[states_count_sorted] # descending order for both names, count 

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'TN', 'CT', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DC', 'DE', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [79]:
loan_string_data[:,5] = np.where(loan_string_data[:,5] == '', 
                                 0, 
                                 loan_string_data[:,5])

In [80]:
# to solve the problem, states all grouped
states_west = np.array(['WA', 'OR', 'CA', 'NV', 'ID', 'MT', 'WY', 'UT', 'CO', 'AZ', 'NM', 'HI', 'AK'])
states_south = np.array(['TX', 'OK', 'AR', 'LA', 'MS', 'AL', 'TN', 'KY', 'FL', 'GA', 'SC', 'NC', 'VA', 'WV', 'MD', 'DE', 'DC'])
states_midwest = np.array(['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO', 'WI', 'IL', 'IN', 'MI', 'OH'])
states_east = np.array(['PA', 'NY', 'NJ', 'CT', 'MA', 'VT', 'NH', 'ME', 'RI'])

In [81]:
loan_string_data[:,5] = np.where(np.isin(loan_string_data[:,5], states_west), 1, loan_string_data[:,5])
loan_string_data[:,5] = np.where(np.isin(loan_string_data[:,5], states_south), 2, loan_string_data[:,5])
loan_string_data[:,5] = np.where(np.isin(loan_string_data[:,5], states_midwest), 3, loan_string_data[:,5])
loan_string_data[:,5] = np.where(np.isin(loan_string_data[:,5], states_east), 4, loan_string_data[:,5])

In [82]:
np.unique(loan_string_data[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Converting to Numbers

In [83]:
loan_string_data

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [84]:
# The function will automatically assign the smallest datatype which succesfully stores all these numbers
loan_string_data = loan_string_data.astype(int)

In [85]:
loan_string_data

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

### Checkpoint 1: Strings

In [86]:
checkpoint_strings = checkpoint('Checkpoint-Strings', header_string, loan_string_data)

In [87]:
checkpoint_strings['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [88]:
checkpoint_strings['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [89]:
# Successfully created checkpoint
np.array_equal(loan_string_data, checkpoint_strings['data'])

True

## Manipulating Numeric columns

In [90]:
loan_numeric_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [91]:
np.isnan(loan_numeric_data).sum()

0

### Subsititute "Filler" Values

In [92]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### ID

In [93]:
temporary_fill

68616520.0

In [94]:
np.isin(loan_numeric_data[:,0], temporary_fill)

array([False, False, False, ..., False, False, False])

In [95]:
np.isin(loan_numeric_data[:,0], temporary_fill).sum()

0

In [96]:
'''
The only column where the minumum value can be considered worst, is the funded amount. Hence, we must switch out all
the fillers in that column for the minimum, while switching fillers and the rest witg maximum recorded value from
each column.
'''
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

### Temporary Stats

In [97]:
# temp_min, temp_mean, temp_max respectively
temporary_stat[:, column_numeric]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

### Funded Amount

In [98]:
loan_numeric_data[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [99]:
loan_numeric_data[:,2] = np.where(loan_numeric_data[:,2] == temporary_fill,
                                 temporary_stat[0, column_numeric[2]],
                                 loan_numeric_data[:,2])
loan_numeric_data[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

### Loaned Amount, Interest Rate, Total Payment, Installment

In [100]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [101]:
for i in [1,3,4,5]:
    loan_numeric_data[:,i] = np.where(loan_numeric_data[:,i] == temporary_fill, 
                                      temporary_stat[2, column_numeric[i]], 
                                      loan_numeric_data[:,i])

In [102]:
loan_numeric_data

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

## Currency

### Exchange Rate

In [103]:
EUR_USD = np.genfromtxt("EUR-USD.csv", 
                     delimiter = ",", 
                     autostrip = True, 
                     skip_header = 1, 
                     usecols = 3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [104]:
loan_string_data[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [105]:
exchange_rate = loan_string_data[:,0]

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i, 
                             EUR_USD[i-1], 
                             exchange_rate)
exchange_rate = np.where(exchange_rate == 0, 
                         np.mean(EUR_USD), 
                         exchange_rate)

In [106]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [107]:
exchange_rate.shape

(10000,)

In [108]:
loan_numeric_data.shape

(10000, 6)

In [109]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [110]:
loan_numeric_data = np.hstack((loan_numeric_data, exchange_rate))

In [111]:
loan_numeric_data

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [112]:
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate'])))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

### From USD to EUR

In [113]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [114]:
columns_dollar = np.array([1,2,4,5])

In [115]:
loan_numeric_data[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [116]:
loan_numeric_data.shape

(10000, 7)

In [117]:
# row index 1 / 6, 2/6, 4/6, 5/6 respectively then hstack
for i in columns_dollar:
    loan_numeric_data = np.hstack((loan_numeric_data, np.reshape(loan_numeric_data[:,i] / loan_numeric_data[:,6], (10000,1))))

In [118]:
loan_numeric_data

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

### Expanding the header

In [119]:
header_additional = np.array([column_name + '_EUR' for column_name in header_numeric[columns_dollar]])

In [120]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [121]:
header_numeric = np.concatenate((header_numeric, header_additional))

In [122]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [123]:
header_numeric[columns_dollar] = np.array([column_name + '_USD' for column_name in header_numeric[columns_dollar]])

In [124]:
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [125]:
column_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [126]:
header_numeric = header_numeric[column_index_order]

In [127]:
loan_numeric_data

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [128]:
loan_numeric_data = loan_numeric_data[:, column_index_order]

## Interest Rate

In [129]:
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [130]:
loan_numeric_data[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [131]:
loan_numeric_data[:,5] = loan_numeric_data[:,5] / 100

In [132]:
loan_numeric_data[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

## Checkpoint 2: Numeric

In [133]:
checkpoint_numeric = checkpoint("Checkpoint-Numeric", header_numeric, loan_numeric_data)

In [134]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

## Creating the Complete Dataset

In [136]:
checkpoint_strings['data'].shape

(10000, 6)

In [137]:
checkpoint_numeric['data'].shape

(10000, 11)

In [140]:
loan_data = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

In [141]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [142]:
np.isnan(loan_data).sum()

0

In [144]:
header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))

## Sorting the New Dataset

In [150]:
loan_data = loan_data[np.argsort(loan_data[:,0])]

In [151]:
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [152]:
np.argsort(loan_data[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999])

## Storing the New Dataset

In [154]:
loan_data = np.vstack((header_full, loan_data))

In [155]:
loan_data

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [156]:
np.savetxt("loan-data-preprocessed.csv", 
           loan_data, 
           fmt = "%s", 
           delimiter = ',')