In [2]:
import numpy as np

## Indexing

In [15]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

## Specific Values

In [16]:
array_a[1]

array([4, 5, 6])

In [17]:
array_a[1][0]

4

In [18]:
array_a[1,0]

4

In [19]:
array_a[:, 0]

array([1, 4])

## Negative Indices

In [20]:
array_b = np.array([1,2,3])
array_b[-1]

3

In [21]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
array_a[-1]

array([4, 5, 6])

## Assigning Values

In [23]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
array_a[0,2] = 9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [25]:
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [26]:
array_a[:, 0] = 9
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [27]:
list_a = [8, 7, 9]
array_a[0] = list_a
array_a

array([[8, 7, 9],
       [9, 5, 6]])

In [28]:
type(array_a[0])

numpy.ndarray

In [29]:
array_a[:] = 9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [30]:
array_a = 9
array_a

9

In [31]:
type(array_a)

int

In [32]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

## Elemetnwise Properties

In [33]:
array_a = np.array([7, 8, 9])
array_a

array([7, 8, 9])

In [34]:
array_b = np.array([[1, 2, 3], [4, 5, 6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
array_b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [36]:
list_a = [1, 2, 3]
list_a + [2]

[1, 2, 3, 2]

In [37]:
array_a + 2

array([ 9, 10, 11])

In [38]:
array_a * array_b[1] # +, -, *, /

array([28, 40, 54])

In [39]:
array_a + array_b # +, -, *, /

array([[ 8, 10, 12],
       [11, 13, 15]])

## Types of Data Supported by NumPy

In [40]:
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
array_a = np.array([[1,2,3], [4,5,6]], dtype = np.float16)
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [42]:
array_a = np.array([[1,2,3], [4,5,6]], dtype = np.complex64)
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [43]:
array_a = np.array([[1,2,0], [4,5,6]], dtype = bool)
array_a

array([[ True,  True, False],
       [ True,  True,  True]])

In [44]:
array_a = np.array([[10,2,3], [4,5,6]], dtype = str)
array_a

array([['10', '2', '3'],
       ['4', '5', '6']], dtype='<U2')

## Characteristics of NumPy Functions

### Universal Functions

https://numpy.org/devdocs/reference/ufuncs.html

### Broadcasting

In [45]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [46]:
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [47]:
matrix_C = np.array([[1, 2, 3], [4, 5, 6]])
matrix_C

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.add(array_a, matrix_C)

array([[2, 4, 6],
       [5, 7, 9]])

In [49]:
np.add(array_b, matrix_C)

array([[2, 3, 4],
       [6, 7, 8]])

### Type Casting

In [50]:
np.add(array_a, matrix_C, dtype = np.float64)

array([[2., 4., 6.],
       [5., 7., 9.]])

In [51]:
'''
Results an error because it convert all numbers into string than tries to add them up 
rather than adding up first and converting them into string later.
'''
np.add(array_a, matrix_C, dtype = np.str)

/var/folders/q7/w_hh_4ds07n_pl9zc0p1wxbc0000gn/T/ipykernel_1093/2923914162.py:5: FutureWarning: In the future `np.str` will be defined as the corresponding NumPy scalar.
  np.add(array_a, matrix_C, dtype = np.str)


AttributeError: module 'numpy' has no attribute 'str'.
`np.str` was a deprecated alias for the builtin `str`. To avoid this error in existing code, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

### Running over an axis

In [52]:
np.mean(matrix_C, axis = 0) # axis = 0 : Finding the mean for each column of the array

array([2.5, 3.5, 4.5])

In [53]:
matrix_C

array([[1, 2, 3],
       [4, 5, 6]])