In [1]:
import numpy as np

## Checking for Missing Values

In [2]:
Lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv", 
                                     delimiter = ',')

In [3]:
np.isnan(Lending_co_data_numeric).sum()

0

In [4]:
lending_co_data_numeric_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv", 
                                            delimiter = ';')

In [5]:
np.isnan(lending_co_data_numeric_nan).sum()

260

In [6]:
temporary_fill = np.nanmax(lending_co_data_numeric_nan).round(2) + 1

In [7]:
temporary_fill

64002.0

In [8]:
lending_co_data_numeric_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv", 
                                            delimiter = ';', 
                                            filling_values = temporary_fill)

In [9]:
np.isnan(lending_co_data_numeric_nan).sum()

0

## Substituting Missing Values

In [10]:
lending_co_data_numeric_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv", 
                                            delimiter = ';')
lending_co_data_numeric_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [11]:
temporary_mean = np.nanmean(lending_co_data_numeric_nan, axis = 0).round(2)

In [12]:
temporary_mean[0]

2250.25

In [13]:
temporary_fill = np.nanmax(lending_co_data_numeric_nan).round(2) + 1

lending_co_data_numeric_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv", 
                                            delimiter = ';', 
                                            filling_values = temporary_fill)

In [14]:
temporary_fill

64002.0

In [15]:
lending_co_data_numeric_nan[:,0] = np.where(lending_co_data_numeric_nan[:,0] == temporary_fill, 
                                            temporary_mean[0], 
                                            lending_co_data_numeric_nan[:,0])

In [16]:
np.mean(lending_co_data_numeric_nan[:,0]).round(2)

2250.25

In [17]:
for i in range(lending_co_data_numeric_nan.shape[1]):
    lending_co_data_numeric_nan[:,i] = np.where(lending_co_data_numeric_nan[:,i] == temporary_fill, 
                                                temporary_mean[i], 
                                                lending_co_data_numeric_nan[:,i])

## Reshaping

In [18]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv",
                                     delimiter = ",")
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [19]:
lending_co_data_numeric.shape

(1043, 6)

In [20]:
np.reshape(lending_co_data_numeric, (6, 1043)) # from flattened arr

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]])

In [21]:
np.transpose(lending_co_data_numeric)

array([[ 2000.,  2000.,  1000., ...,  2000.,  1000.,  2000.],
       [   40.,    40.,    40., ...,    40.,    40.,    40.],
       [  365.,   365.,   365., ...,   365.,   365.,   365.],
       [ 3121.,  3061.,  2160., ...,  4201.,  2080.,  4601.],
       [ 4241.,  4171.,  3280., ...,  5001.,  3320.,  4601.],
       [13621., 15041., 15340., ..., 16600., 15600., 16600.]])

In [22]:
np.reshape(lending_co_data_numeric, (2, 3, 1043))

array([[[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
        [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
        [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.]],

       [[ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
        [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
        [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]]])

In [23]:
lending_co_data_numeric_rshp = np.reshape(lending_co_data_numeric, (6, 1043))
lending_co_data_numeric_rshp

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]])

In [24]:
lending_co_data_numeric.reshape(6,1043)

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]])

## Removing Values

In [25]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv", delimiter = ',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [26]:
np.delete(lending_co_data_numeric, 0).shape

(6257,)

In [27]:
lending_co_data_numeric.size

6258

In [28]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [29]:
np.delete(lending_co_data_numeric, (0,2,4), axis = 1)

array([[   40.,  3121., 13621.],
       [   40.,  3061., 15041.],
       [   40.,  2160., 15340.],
       ...,
       [   40.,  4201., 16600.],
       [   40.,  2080., 15600.],
       [   40.,  4601., 16600.]])

In [30]:
np.delete(np.delete(lending_co_data_numeric, (0,2,4), axis = 1), (0,2,-1), axis = 0)

array([[   40.,  3061., 15041.],
       [   40.,  3041., 15321.],
       [   50.,  3470., 13720.],
       ...,
       [   40.,  4240., 16600.],
       [   40.,  4201., 16600.],
       [   40.,  2080., 15600.]])

## Sorting Data

In [31]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv",
                                     delimiter = ",")
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [32]:
# Default axis = -1, rearranging the different columns in every row 
np.sort(lending_co_data_numeric)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]])

In [33]:
lending_co_data_numeric.shape

(1043, 6)

In [34]:
np.sort(lending_co_data_numeric).shape

(1043, 6)

In [35]:
np.sort(lending_co_data_numeric, axis = 0)

array([[ 1.0000e+03,  3.5000e+01,  3.6500e+02, -2.8700e+03, -2.8700e+03,
        -3.5000e+02],
       [ 1.0000e+03,  3.5000e+01,  3.6500e+02, -2.5500e+03, -2.1000e+03,
         1.5000e+02],
       [ 1.0000e+03,  3.5000e+01,  3.6500e+02, -2.4500e+03, -2.0000e+03,
         1.1000e+03],
       ...,
       [ 9.0000e+03,  1.2500e+02,  3.6500e+02,  1.6751e+04,  1.8751e+04,
         5.4625e+04],
       [ 9.0000e+03,  1.6500e+02,  3.6500e+02,  1.7650e+04,  2.0001e+04,
         5.4625e+04],
       [ 9.0000e+03,  1.6500e+02,  3.6500e+02,  1.9001e+04,  2.2001e+04,
         6.4001e+04]])

In [36]:
# THESE SETTINGS WILL APPLY TO OUR ENTIRE WORK !!
np.set_printoptions(suppress = True)

In [37]:
np.sort(lending_co_data_numeric, axis = None) # flattened

array([-2870., -2870., -2550., ..., 54625., 54625., 64001.])

In [38]:
np.sort(lending_co_data_numeric)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]])

In [39]:
'''
The minus sign within the parentheses changes all the elements of the data set to sort them in descending order,
while the minus sign at the start of the line reverses the change of the elements' value and return them to normal.
'''
-np.sort(-lending_co_data_numeric)

array([[13621.,  4241.,  3121.,  2000.,   365.,    40.],
       [15041.,  4171.,  3061.,  2000.,   365.,    40.],
       [15340.,  3280.,  2160.,  1000.,   365.,    40.],
       ...,
       [16600.,  5001.,  4201.,  2000.,   365.,    40.],
       [15600.,  3320.,  2080.,  1000.,   365.,    40.],
       [16600.,  4601.,  4601.,  2000.,   365.,    40.]])

In [40]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [41]:
# Take the array variable, sorts it, stores the sorted version over the original
lending_co_data_numeric.sort(axis = 0)
lending_co_data_numeric

array([[ 1000.,    35.,   365., -2870., -2870.,  -350.],
       [ 1000.,    35.,   365., -2550., -2100.,   150.],
       [ 1000.,    35.,   365., -2450., -2000.,  1100.],
       ...,
       [ 9000.,   125.,   365., 16751., 18751., 54625.],
       [ 9000.,   165.,   365., 17650., 20001., 54625.],
       [ 9000.,   165.,   365., 19001., 22001., 64001.]])

## Argument Functions

### np.argsort()

In [42]:
lending_co_data_numeric = np.loadtxt('Lending-company-Numeric.csv', 
                                     delimiter = ",")
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [43]:
np.argsort(lending_co_data_numeric)

array([[1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       ...,
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5]])

In [44]:
np.sort(lending_co_data_numeric, axis = 0)

array([[ 1000.,    35.,   365., -2870., -2870.,  -350.],
       [ 1000.,    35.,   365., -2550., -2100.,   150.],
       [ 1000.,    35.,   365., -2450., -2000.,  1100.],
       ...,
       [ 9000.,   125.,   365., 16751., 18751., 54625.],
       [ 9000.,   165.,   365., 17650., 20001., 54625.],
       [ 9000.,   165.,   365., 19001., 22001., 64001.]])

In [45]:
np.argsort(lending_co_data_numeric, axis = 0)

array([[  32,  816, 1016,   32,   32,  482],
       [  34,  432, 1017,  166,  166,  493],
       [ 995,  443, 1018,   85,   85,  166],
       ...,
       [ 568, 1033, 1041,  568, 1019, 1033],
       [ 152,  408, 1042,  718, 1033,  912],
       [ 153,   27,    0,  912,  912,   27]])

In [46]:
lending_co_data_numeric[482, 5]

-350.0

In [47]:
lending_co_data_numeric = lending_co_data_numeric[np.argsort(lending_co_data_numeric[:,0])]
lending_co_data_numeric

array([[ 1000.,    50.,   365., -2870., -2870.,  1160.],
       [ 1000.,    50.,   365.,   250.,   850.,  5050.],
       [ 1000.,    40.,   365.,  2220.,  3440., 15600.],
       ...,
       [ 9000.,   125.,   365., 16751., 16751., 54625.],
       [ 9000.,   125.,   365., 12251., 15626., 34514.],
       [ 9000.,   125.,   365., 11751., 15451., 26876.]])

In [48]:
lending_co_data_numeric.argsort(axis = 0) # the method does not overwrite the original array

array([[  39,   49, 1016,    0,    0,  158],
       [  40,  194, 1017,  132,  132,  145],
       [  41,  164, 1018,   44,   44,  132],
       ...,
       [1040, 1041, 1041, 1040, 1024, 1037],
       [1041, 1028, 1042,  846, 1023, 1036],
       [1042, 1030,    0, 1039, 1039, 1030]])

In [49]:
lending_co_data_numeric

array([[ 1000.,    50.,   365., -2870., -2870.,  1160.],
       [ 1000.,    50.,   365.,   250.,   850.,  5050.],
       [ 1000.,    40.,   365.,  2220.,  3440., 15600.],
       ...,
       [ 9000.,   125.,   365., 16751., 16751., 54625.],
       [ 9000.,   125.,   365., 12251., 15626., 34514.],
       [ 9000.,   125.,   365., 11751., 15451., 26876.]])

### np.argwhere()

In [50]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv", delimiter = ",")
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [51]:
# default condition is to check for values different from 0
# row | col
np.argwhere(lending_co_data_numeric)

array([[   0,    0],
       [   0,    1],
       [   0,    2],
       ...,
       [1042,    3],
       [1042,    4],
       [1042,    5]])

In [52]:
np.argwhere(lending_co_data_numeric == False)

array([[116,   4],
       [430,   3]])

In [53]:
lending_co_data_numeric[116]

array([ 1000.,    50.,   365., -1450.,     0., 13850.])

In [54]:
np.argwhere(lending_co_data_numeric % 2 == 0)

array([[   0,    0],
       [   0,    1],
       [   1,    0],
       ...,
       [1042,    0],
       [1042,    1],
       [1042,    5]])

In [55]:
np.isnan(lending_co_data_numeric).sum()

0

In [56]:
lending_co_data_numeric_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter = ';')
lending_co_data_numeric_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [57]:
# returns coordinates of nan
np.argwhere(np.isnan(lending_co_data_numeric_nan))

array([[  11,    3],
       [  15,    3],
       [  27,    3],
       [  58,    3],
       [  60,    4],
       [  85,    4],
       [ 117,    5],
       [ 152,    1],
       [ 152,    2],
       [ 152,    4],
       [ 172,    1],
       [ 175,    1],
       [ 175,    2],
       [ 176,    3],
       [ 177,    4],
       [ 178,    5],
       [ 211,    3],
       [ 229,    0],
       [ 230,    1],
       [ 237,    1],
       [ 247,    3],
       [ 251,    5],
       [ 252,    4],
       [ 258,    1],
       [ 260,    3],
       [ 262,    4],
       [ 271,    5],
       [ 272,    4],
       [ 284,    2],
       [ 284,    3],
       [ 297,    1],
       [ 297,    2],
       [ 300,    3],
       [ 315,    3],
       [ 315,    5],
       [ 327,    4],
       [ 336,    4],
       [ 343,    0],
       [ 344,    2],
       [ 346,    2],
       [ 363,    3],
       [ 375,    3],
       [ 377,    2],
       [ 398,    5],
       [ 416,    4],
       [ 428,    0],
       [ 432,    1],
       [ 433,

In [58]:
lending_co_data_numeric_nan[152]

array([ 9000.,    nan,    nan, 12251.,    nan, 34514.])

In [59]:
# find coordinates of nan set row-col to zero
for array_index in np.argwhere(np.isnan(lending_co_data_numeric_nan)):
    lending_co_data_numeric_nan[array_index[0], array_index[1]] = 0

In [60]:
lending_co_data_numeric_nan[175]

array([ 2000.,     0.,     0.,  1851.,  3051., 13561.])

In [61]:
np.isnan(lending_co_data_numeric_nan).sum()

0

## Shuffling Data

In [62]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv",
                                     delimiter = ",")
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [63]:
np.random.shuffle(lending_co_data_numeric) # for each shuffle we'll get a different outcome

In [64]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  4601.,  7001., 16600.],
       [ 2000.,    50.,   365.,  3100.,  4500., 16850.],
       [ 1000.,    50.,   365., -1300.,  -850., 11401.],
       ...,
       [ 1000.,    35.,   365.,  2295.,  3065.,  3135.],
       [ 2000.,    40.,   365.,  3641.,  4841., 16311.],
       [ 2000.,    40.,   365.,  4201.,  6601., 16600.]])

In [65]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv",
                                     delimiter = ",")
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [66]:
from numpy.random import shuffle

In [67]:
shuffle(lending_co_data_numeric)
lending_co_data_numeric

array([[ 9000.,   125.,   365., 12001., 15751., 38626.],
       [ 1000.,    40.,   365.,  2200.,  3400., 15600.],
       [ 2000.,    40.,   365.,  3560.,  4740., 14020.],
       ...,
       [ 2000.,    50.,   365.,  4501.,  7001., 20250.],
       [ 2000.,    50.,   365.,  5000.,  6000., 20250.],
       [ 1000.,    40.,   365.,  3100.,  3700., 12720.]])

In [68]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [69]:
array_RG = gen(pcg())
array_RG.shuffle(lending_co_data_numeric)
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  4621.,  4621., 16600.],
       [ 4000.,    50.,   365.,  7250.,  8750., 22250.],
       [ 2000.,    40.,   365.,  3401.,  4871., 16600.],
       ...,
       [ 2000.,    40.,   365.,  5801.,  5801., 16600.],
       [ 1000.,    40.,   365.,  2360.,  3360., 15110.],
       [ 2000.,    40.,   365.,  3201.,  4301., 12191.]])

## Casting

In [70]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv", 
                                     delimiter = ",")
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [71]:
lending_co_data_numeric.astype(dtype = np.int32)

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       ...,
       [ 2000,    40,   365,  4201,  5001, 16600],
       [ 1000,    40,   365,  2080,  3320, 15600],
       [ 2000,    40,   365,  4601,  4601, 16600]], dtype=int32)

In [72]:
# Cannot type cast 
lending_co_data_numeric = lending_co_data_numeric.astype(dtype = str)

In [73]:
type(lending_co_data_numeric)

numpy.ndarray

In [74]:
# We cannot directly cast string to integers
# lending_co_data_numeric.astype(dtype = np.int32)

lending_co_data_numeric = lending_co_data_numeric.astype(dtype = np.float32)
lending_co_data_numeric.astype(dtype = np.int32)

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       ...,
       [ 2000,    40,   365,  4201,  5001, 16600],
       [ 1000,    40,   365,  2080,  3320, 15600],
       [ 2000,    40,   365,  4601,  4601, 16600]], dtype=int32)

In [75]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv", 
                                     delimiter = ",")
lending_co_data_numeric = lending_co_data_numeric.astype(dtype = str)
lending_co_data_numeric

array([['2000.0', '40.0', '365.0', '3121.0', '4241.0', '13621.0'],
       ['2000.0', '40.0', '365.0', '3061.0', '4171.0', '15041.0'],
       ['1000.0', '40.0', '365.0', '2160.0', '3280.0', '15340.0'],
       ...,
       ['2000.0', '40.0', '365.0', '4201.0', '5001.0', '16600.0'],
       ['1000.0', '40.0', '365.0', '2080.0', '3320.0', '15600.0'],
       ['2000.0', '40.0', '365.0', '4601.0', '4601.0', '16600.0']],
      dtype='<U32')

In [76]:
lending_co_data_numeric.astype(dtype = np.float32).astype(dtype = np.int32) # cast from left to right

array([[ 2000,    40,   365,  3121,  4241, 13621],
       [ 2000,    40,   365,  3061,  4171, 15041],
       [ 1000,    40,   365,  2160,  3280, 15340],
       ...,
       [ 2000,    40,   365,  4201,  5001, 16600],
       [ 1000,    40,   365,  2080,  3320, 15600],
       [ 2000,    40,   365,  4601,  4601, 16600]], dtype=int32)

## Stripping Values

In [78]:
lending_co_tot_price = np.genfromtxt("Lending-Company-Total-Price.csv", 
                                     delimiter = ',', 
                                     dtype = str, 
                                     skip_header = 1, 
                                     usecols = [1,2,4])
lending_co_tot_price

array([['id_1', 'Product B', 'Location 2'],
       ['id_2', 'Product B', 'Location 3'],
       ['id_3', 'Product C', 'Location 5'],
       ...,
       ['id_413', 'Product B', 'Location 135'],
       ['id_414', 'Product C', 'Location 200'],
       ['id_415', 'Product A', 'Location 8']], dtype='<U12')

In [83]:
lending_co_tot_price[:,0] = np.chararray.strip(lending_co_tot_price[:,0], "id_")
lending_co_tot_price[:,1] = np.chararray.strip(lending_co_tot_price[:,1], "Product ")
lending_co_tot_price[:,2] = np.chararray.strip(lending_co_tot_price[:,2], "Location ")
lending_co_tot_price

array([['1', 'B', '2'],
       ['2', 'B', '3'],
       ['3', 'C', '5'],
       ...,
       ['413', 'B', '135'],
       ['414', 'C', '200'],
       ['415', 'A', '8']], dtype='<U12')

In [84]:
lending_co_tot_price[:,1] = np.where(lending_co_tot_price[:,1] == 'A', 1, lending_co_tot_price[:,1])
lending_co_tot_price[:,1] = np.where(lending_co_tot_price[:,1] == 'B', 1, lending_co_tot_price[:,1])
lending_co_tot_price[:,1] = np.where(lending_co_tot_price[:,1] == 'C', 1, lending_co_tot_price[:,1])
lending_co_tot_price[:,1] = np.where(lending_co_tot_price[:,1] == 'D', 1, lending_co_tot_price[:,1])
lending_co_tot_price[:,1] = np.where(lending_co_tot_price[:,1] == 'E', 1, lending_co_tot_price[:,1])
lending_co_tot_price[:,1] = np.where(lending_co_tot_price[:,1] == 'F', 1, lending_co_tot_price[:,1])

lending_co_tot_price

array([['1', '1', '2'],
       ['2', '1', '3'],
       ['3', '1', '5'],
       ...,
       ['413', '1', '135'],
       ['414', '1', '200'],
       ['415', '1', '8']], dtype='<U12')

In [86]:
lending_co_tot_price = lending_co_tot_price.astype(dtype = np.int32)
lending_co_tot_price

array([[  1,   1,   2],
       [  2,   1,   3],
       [  3,   1,   5],
       ...,
       [413,   1, 135],
       [414,   1, 200],
       [415,   1,   8]], dtype=int32)

## Stacking 

In [87]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv", delimiter = ',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [90]:
lending_co_data_numeric_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter = ';')

temporary_fill = np.nanmax(lending_co_data_numeric_nan).round(2) + 1
temporary_mean = np.nanmean(lending_co_data_numeric_nan, axis = 0).round(2)

lending_co_data_numeric_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv", 
                                            delimiter = ';', 
                                            filling_values = temporary_fill)

for i in range(lending_co_data_numeric_nan.shape[1]):
    lending_co_data_numeric_nan[:,i] = np.where(lending_co_data_numeric_nan[:,i] == temporary_fill, 
                                                temporary_mean[i], 
                                                lending_co_data_numeric_nan[:,i])
lending_co_data_numeric_nan

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [93]:
np.stack((lending_co_data_numeric_nan[:,0], lending_co_data_numeric_nan[:,1]))

array([[2000.  , 2000.  , 1000.  , ..., 2250.25, 1000.  , 2000.  ],
       [  40.  ,   40.  ,   40.  , ...,   40.  ,   40.  ,   40.  ]])

In [94]:
# the arrays must havve the same shape
np.stack((lending_co_data_numeric_nan[:,0], lending_co_data_numeric_nan[:,1]), axis = 1)

array([[2000.  ,   40.  ],
       [2000.  ,   40.  ],
       [1000.  ,   40.  ],
       ...,
       [2250.25,   40.  ],
       [1000.  ,   40.  ],
       [2000.  ,   40.  ]])

In [95]:
np.vstack((lending_co_data_numeric, lending_co_data_numeric_nan))

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [96]:
np.vstack((lending_co_data_numeric, lending_co_data_numeric_nan)).shape

(2086, 6)

In [97]:
np.hstack((lending_co_data_numeric, lending_co_data_numeric_nan))

array([[ 2000.,    40.,   365., ...,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365., ...,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365., ...,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365., ...,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365., ...,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365., ...,  4601.,  4601., 16600.]])

In [98]:
np.hstack((lending_co_data_numeric, lending_co_data_numeric_nan)).shape

(1043, 12)

In [99]:
# returns an array of a higher dimension
np.dstack((lending_co_data_numeric, lending_co_data_numeric_nan))

array([[[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 3121.  ,  3121.  ],
        [ 4241.  ,  4241.  ],
        [13621.  , 13621.  ]],

       [[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 3061.  ,  3061.  ],
        [ 4171.  ,  4171.  ],
        [15041.  , 15041.  ]],

       [[ 1000.  ,  1000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 2160.  ,  2160.  ],
        [ 3280.  ,  3280.  ],
        [15340.  , 15340.  ]],

       ...,

       [[ 2000.  ,  2250.25],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 4201.  ,  4201.  ],
        [ 5001.  ,  5001.  ],
        [16600.  , 16600.  ]],

       [[ 1000.  ,  1000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 2080.  ,  2080.  ],
        [ 3320.  ,  3320.  ],
        [15600.  , 15600.  ]],

       [[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  

In [100]:
np.dstack((lending_co_data_numeric, lending_co_data_numeric_nan)).shape # row - col - original array

(1043, 6, 2)

## Concatenate

In [101]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv", delimiter = ',')
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [102]:
'''
Differs from stacking because even though we're storing the values of both arrays, we're still confined to 1 dimension
'''
np.concatenate((lending_co_data_numeric[0,:], lending_co_data_numeric[1,:]))

array([ 2000.,    40.,   365.,  3121.,  4241., 13621.,  2000.,    40.,
         365.,  3061.,  4171., 15041.])

In [103]:
lending_co_data_numeric_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter = ';')

temporary_fill = np.nanmax(lending_co_data_numeric_nan).round(2) + 1
temporary_mean = np.nanmean(lending_co_data_numeric_nan, axis = 0).round(2)

lending_co_data_numeric_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv", 
                                            delimiter = ';', 
                                            filling_values = temporary_fill)

for i in range(lending_co_data_numeric_nan.shape[1]):
    lending_co_data_numeric_nan[:,i] = np.where(lending_co_data_numeric_nan[:,i] == temporary_fill, 
                                                temporary_mean[i], 
                                                lending_co_data_numeric_nan[:,i])
lending_co_data_numeric_nan

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [104]:
# We've concatenated the second dataset at the bottom of the first
np.concatenate((lending_co_data_numeric, lending_co_data_numeric_nan))

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [105]:
np.concatenate((lending_co_data_numeric, lending_co_data_numeric_nan)).shape

(2086, 6)

In [106]:
np.concatenate((lending_co_data_numeric, lending_co_data_numeric_nan),axis = 1)

array([[ 2000.,    40.,   365., ...,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365., ...,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365., ...,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365., ...,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365., ...,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365., ...,  4601.,  4601., 16600.]])

In [107]:
np.concatenate((lending_co_data_numeric, lending_co_data_numeric_nan),axis = 1).shape

(1043, 12)

In [108]:
array_example_1 = np.array([[[1,2,3,4], [5,6,7,8], [6,7,8,9], [9,10,11,12], [21,22,23,24], [25,26,27,28], [29,30,31,32]]])
array_example_2 = array_example_1 * 2

In [110]:
np.concatenate((array_example_1, array_example_2), axis = 0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 6,  7,  8,  9],
        [ 9, 10, 11, 12],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [12, 14, 16, 18],
        [18, 20, 22, 24],
        [42, 44, 46, 48],
        [50, 52, 54, 56],
        [58, 60, 62, 64]]])

In [113]:
np.vstack((array_example_1, array_example_2))

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 6,  7,  8,  9],
        [ 9, 10, 11, 12],
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32]],

       [[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [12, 14, 16, 18],
        [18, 20, 22, 24],
        [42, 44, 46, 48],
        [50, 52, 54, 56],
        [58, 60, 62, 64]]])

## Unique

In [114]:
lending_co_data_numeric = np.loadtxt("Lending-company-Numeric.csv", 
                                     delimiter = ",")
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [115]:
np.unique(lending_co_data_numeric[:,1], return_counts = True, return_index = True)

(array([ 35.,  40.,  50., 125., 165.]),
 array([327,   0,   4,  19,  27]),
 array([  4, 567, 451,  19,   2]))

In [116]:
array_example = np.array(["a1", "a3", "A1", "A3", "AA1", "B1", "A2", "B1", "A2", "B2", "B2", "B3", "a2", "a3", "B3", "B3", "a3"])
np.unique(array_example)

array(['A1', 'A2', 'A3', 'AA1', 'B1', 'B2', 'B3', 'a1', 'a2', 'a3'],
      dtype='<U3')