__Import the relevant libraries__

In [3]:
import numpy as np

__Declaring scalars, vectors, and matrices__

**Scalars**

In [4]:
s = 5

In [5]:
s

5

__Vectors__

In [6]:
v = np.array([5, -2 ,4])

In [7]:
v # By default 'v' is a row vector 

array([ 5, -2,  4])

**Matrices**

In [11]:
m = np.array([[5, 12 ,6], [-3, 0, 14]])

In [12]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

**Data Types**

In [13]:
type(s)

int

In [14]:
type(v) # 1-dimensional array

numpy.ndarray

In [15]:
type(m) # 2-dimensional array

numpy.ndarray

In [16]:
s_array = np.array(5) # another way to creating scalar 
s_array

array(5)

In [18]:
type(s_array)

numpy.ndarray

**Data Shapes**

In [20]:
# shape returns the shape(dimensinoss of variable)
m.shape

(2, 3)

In [21]:
v.shape

(3,)

In [24]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [25]:
s_array.shape # scalars don't have dimensions

()

**Creating a Column Vector**

In [22]:
v.reshape(1,3) # row vector

array([[ 5, -2,  4]])

In [23]:
v.reshape(3,1) # column vector

array([[ 5],
       [-2],
       [ 4]])