**Import the relevant libraries**

In [1]:
import numpy as np

**Creating a Tensor**

In [4]:
m1 = np.array([[5, 12, 6],[-3, 0, 14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [5]:
m2 = np.array([[9, 8, 7],[1, 3, -5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [6]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

**Checking its shape**

In [7]:
t.shape # 2 matrices 2 by 3 each

(2, 2, 3)

**Manually creating a tensor**

In [10]:
t_manual = np.array([ [[5, 12, 6], [-3 ,0, 14]], [[9, 8, 7], [1, 3, -5]] ])
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])